language: node_js
node_js:
 - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
 - npm install hexo
 - npm install hexo --save
 - npm install
script:
 - hexo clean
 - hexo generate
 - chmod +x ./push.sh
 - ./push.sh > /dev/null
branches:
 only:
  - hexo-branch