language: node_js
node_js:
 - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
 - npm install hexo
 - npm install hexo --save
 - npm install
script:
 - hexo clean
 - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: ./public
  email: "453476815@qq.com"
  name: "Travis CI Auto Builder"
  on:
    branch:master
  target_branch: master
branches:
 only:
  - hexo-branch
